### PR TITLE
Add namespace support for NFS deployment and simple fixes

### LINKED ISSUE #24: PVC operator looks up deployment using hard coded values
PVC operator looks up deployment using hard coded values: https://github.com/banzaicloud/pvc-operator/blob/master/pkg/stub/providers/common.go#L118

These values should not be hardcoded but rather received as config during deployment.

Pipeline deploys PVC operator using helm chart: ttps://github.com/banzaicloud/pipeline/blob/master/cluster/hooks.go#L712
cluster/hooks.go:712 which results in PVC operator K8s deployment with varying name. If

### PR DESCRIPTION
**Pull request by baluchicken**
Fixes #24

### CODE REVIEW

File: pkg/stub/providers/nfs.go [hunk 1]
```diff
@@ -90,7 +94,7 @@ func SetUpNfsProvisioner(pv *v1.PersistentVolumeClaim) error {
 		},
 		ObjectMeta: metav1.ObjectMeta{
 			Name:      "nfs-provisioner",
-			Namespace: "default",
+			Namespace: nfsNamespace,
```
Comment (stoader) [inline pkg/stub/providers/nfs.go]: Factor out `nfs-provisioner` into a const as it is used in multiple places.

**Review by stoader — CHANGES_REQUESTED** [review]

**Review by stoader — APPROVED** [review]
LGTM

**Review by bonifaido — APPROVED** [review]
LGTM
